spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/clubmanagementsystem}
    username: ${JDBC_DATABASE_USERNAME:myuser}
    password: ${JDBC_DATABASE_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
jwt:
  secret: ${JWT_SECRET:YourVerySecretKeyHere}
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


